In [17]:
import pandas as pd
import mysql.connector as lol
import json
import collections
from sys import path
import pyodbc 



conn_mysql = lol.connect(user='root', password='P@ssw0rd',host='localhost',database='cowpay_staging')
conn_sql = pyodbc.connect('Driver={SQL Server};Server=BI-SERVER2022;PORT=1433;Database=Staging_Migration;Trusted_Connection=yes;')

cursor = conn_mysql.cursor()
my_data = pd.read_sql("select *, case when block = 0 and is_merchant = 1 then 'approved' when block = 1 and is_merchant = 1 then 'Suspended' end as status from cowpay_staging.users where is_merchant=1;",conn_mysql)
my_data.to_dict()
my_data
#my_data.style.hide_index()
#print(my_data.to_string(index=False))
#df1 = my_data.to_string(index=False)
#print(df1)

,id,parent_id,name,email,phone,password,api_token,remember_token,created_at,updated_at,...,environment,block,name_ar,category,mid_category,contract_file,authorize_signatory_name,fawry_sub_merchant,cowpay_fees,status
0,2,None,Khaled Mohamed,engkhaledmohamed1991@gmail.com,01118009869,$2y$10$wAWrsDLFKgVN7WwmE3tcs.i4aKotixUBV7rIkg8...,ac90cc93ce15fa77c38fbb89555d34c1d341255524af3d...,oBS92G4G5QDTfaS93SCOHzijiSsA9ZGC0UTL2mMWYIfL6N...,2019-03-31 11:32:17,2022-07-26 02:00:02,...,PRODUCTION,0,,,,,,None,1.5,approved
1,3,None,Miracle Nassif Store,nassif.mira@gmail.com,+201030031133,$2y$10$r7TJhWn5XIkP/3kv6arNouB29aafY.eawxSBJCq...,a8b6a5fbda4c5fa9f617f3507a51f594b73883a79f7161...,RSUpKwR5zBIxDnocAuOwAxF1ahvcqdwKOTtwkHIAUTjSLt...,2019-04-01 15:31:50,2022-07-26 02:00:02,...,PRODUCTION,1,,,,,,None,1.5,Suspended
2,4,None,Dev Testing,freelancers@gmail.com,01118000000,$2y$10$wAWrsDLFKgVN7WwmE3tcs.i4aKotixUBV7rIkg8...,,,2019-03-31 11:32:17,2022-07-26 02:00:02,...,PRODUCTION,0,,,,,,None,1.5,approved
3,8,None,Ibrahim Konsowa,ibrahim.konsowa96@gmail.com,01113699632,$2y$10$9ZezlAKz6yH7884to20csOnI0SGFOlwVGUmO.ZY...,None,FRktiD1kkaR0Oj8bCLMbY8p2Il9g1OjdWd3kVz5KIdLj55...,2019-03-27 14:55:29,2022-07-26 02:00:02,...,PRODUCTION,0,,,,,,None,1.5,approved
4,9,None,TechneSummit,tarek.elkady@kdgp.net,01098950608,$2y$10$4wNN7/Hx0o0rZdv6HTkU7O5HGw7kaQLr/G5KLPb...,76cc0235701769f3d869bda1adff871e9ba1e4144f4095...,q2tV6bFxLAvKw0cZejfCVZImDIUNbxdEAIDIYtAQb2MWjK...,2019-07-07 18:01:50,2022-07-26 02:00:02,...,PRODUCTION,0,,,,,,None,1.5,approved
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615,888,None,yasmin alwaan,yasmin.alwaan@linktsp.com,01111391269,$2y$10$hP8UlQaSdtgk0wRrF2jqC.d6VqsFmBivYLs.423...,None,None,2022-04-14 17:39:29,2022-07-26 02:00:06,...,PRODUCTION,0,,,,,,None,0.0,approved
616,889,None,nic-cart eg,mohamed.khalaf@cowpay.me,01094356579,$2y$10$J9ZrZotwPGz5YkomgB0vCuEemiCmKDoZBOX5s/....,None,None,2022-04-14 18:03:27,2022-07-02 22:27:22,...,PRODUCTION,0,,,,,,None,0.0,approved
617,890,None,Excel-test,Excel-test@cowpay.me,01123469492,$2y$10$Ubc1HBwhdAAx0xGrCwpek.rg1KVSU2h3ifQ1Xbz...,None,None,2022-05-18 18:32:59,2022-07-24 16:39:14,...,PRODUCTION,0,,,,,,None,1.5,approved
618,891,None,demo accounttt,demo_account213@gmail.com,01112112520,$2y$10$fxhticayxqBYfRJwrek/que99VDL1Jw7b535piv...,None,None,2022-07-07 13:46:08,2022-07-26 02:00:06,...,PRODUCTION,0,,,,,,None,1.5,approved
619,892,None,checkout,checkout@gmail.com,01005620648,$2y$10$PV7sm8pSigSfbmkNwHrha.2DKhtz8J9JSSVoEtd...,None,None,2022-07-24 12:20:50,2022-07-26 12:36:53,...,PRODUCTION,0,,,,,,None,1.5,approved

In [18]:
class create_dict(dict): 
  
    # __init__ function 
    def __init__(self): 
        self = dict() 
          
    # Function to add key:value 
    def add(self, key, value): 
        self[key] = value

mydict = create_dict()
settings = """select id, null,null ,null,m_callback_url,m_payments_notification,m_orders_notification,m_cowpay_payatfawry_percentage_commission,m_cowpay_payatfawry_fixed_commission,m_cowpay_credit_card_percentage_commission,m_cowpay_credit_card_fixed_commission,m_cowpay_collect_percentage_commission,m_cowpay_collect_fixed_commission,m_available_balance,m_commercial_registry_file,m_tax_id_file,m_personal_id_file from cowpay_staging.users where is_merchant=1"""
cursor = conn_mysql.cursor()
cursor.execute(settings)
result = cursor.fetchall()
settings_dict={'id':[],'json_settings':[]}
for row in result:
    settings_id=row[0]
    settings_data = [
           
    {
        "id": "",
        "merchantCode": row[1],
        "StatusTypeId": row[1],
        "moreSetting": {"m_callback_url": row[5], "m_payments_notification": row[6],"m_orders_notification":row[7]},
        "limitationNBlocking":[],
        "financialConfig":{"comessions":[{"payMethodType":2,"fixedVal":row[8],"percentage":row[7],"isEnabled":'true' },
                                         {"payMethodType":1,"fixedVal":row[10],"percentage":row[9],"isEnabled":'true'},
                                         {"payMethodType":6,"fixedVal":row[12],"percentage":row[11],"isEnabled":'true'}
                                        ],
        "autoWithdrawal":{"isEnabled":"","peroidType":"","monthDay":"","daysValue":"","day":""},
        "b2b":{"isEnabled":"","fixedVal":"","percentage":""},
        "chashout":{"isEnabled":"","values":[]}},
         "balanceConfiguration":{"m_available_balance":row[13]}
         },
          
  
]
    settings_dict['id'].append(settings_id)
    settings_dict['json_settings'].append(json.dumps(settings_data))
#s_json = json.dumps(settings_list)

s_json =pd.DataFrame(settings_dict)
#df2 = s_json.to_string(index=False)
#print(df1)
#s_json.to_csv('s.csv')
#print(s_json.to_string(index=False))
s_json
#display(df.hide_index())
#df2

      id                                      json_settings
0      2  [{"id": "", "merchantCode": null, "StatusTypeI...
1      3  [{"id": "", "merchantCode": null, "StatusTypeI...
2      4  [{"id": "", "merchantCode": null, "StatusTypeI...
3      8  [{"id": "", "merchantCode": null, "StatusTypeI...
4      9  [{"id": "", "merchantCode": null, "StatusTypeI...
..   ...                                                ...
615  888  [{"id": "", "merchantCode": null, "StatusTypeI...
616  889  [{"id": "", "merchantCode": null, "StatusTypeI...
617  890  [{"id": "", "merchantCode": null, "StatusTypeI...
618  891  [{"id": "", "merchantCode": null, "StatusTypeI...
619  892  [{"id": "", "merchantCode": null, "StatusTypeI...

[620 rows x 2 columns]

In [19]:
import json
select_Users = """SELECT id,m_facebook,m_twitter,m_linked_in,m_instagram,m_website FROM cowpay_staging.users where is_merchant=1"""
cursor = conn_mysql.cursor()
cursor.execute(select_Users)
result = cursor.fetchall()
Urls_dict={'id':[],'Urls_settings':[]}
for row in result:
    url_id=row[0]
    url_data = [
      {      
    
        "SocialUrl": row[1],
        "SocialType": {"id": "1", "Name": "Facebook","Icon":"fab fa-facebook-f"}
        
    },
          
    {
       "SocialUrl": row[2],
        "SocialType": {"id": "2", "Name": "Twitter","Icon":"fab fa-twitter"},
    },
    {
        "SocialUrl": row[3],
        "SocialType": {"id": "3", "Name": "LinkedIn","Icon":"fas fa-link"},
    },
    {
        "SocialUrl": row[4],
        "SocialType": {"id": "5", "Name": "m_instagram","Icon":"fas fa-instagram"},
    },
        
    {
        "SocialUrl": row[5],
        "SocialType": {"id": "4", "Name": "Website","Icon":""},
    }
      
        ]
  
    Urls_dict['id'].append(url_id)
    Urls_dict['Urls_settings'].append(json.dumps(url_data))
#s_json = json.dumps(settings_list)

u_json =pd.DataFrame(Urls_dict)
u_json
#u_json.to_csv('u.csv')

    #list.append(data)
    #print(data)
#stud_json = json.dumps(list)

#stud_json
#list

      id                                      Urls_settings
0      2  [{"SocialUrl": null, "SocialType": {"id": "1",...
1      3  [{"SocialUrl": null, "SocialType": {"id": "1",...
2      4  [{"SocialUrl": null, "SocialType": {"id": "1",...
3      8  [{"SocialUrl": null, "SocialType": {"id": "1",...
4      9  [{"SocialUrl": null, "SocialType": {"id": "1",...
..   ...                                                ...
615  888  [{"SocialUrl": null, "SocialType": {"id": "1",...
616  889  [{"SocialUrl": null, "SocialType": {"id": "1",...
617  890  [{"SocialUrl": null, "SocialType": {"id": "1",...
618  891  [{"SocialUrl": null, "SocialType": {"id": "1",...
619  892  [{"SocialUrl": null, "SocialType": {"id": "1",...

[620 rows x 2 columns]

In [21]:
import json

select_Usersss= """SELECT id,m_commercial_registry_file,m_tax_id_file,m_personal_id_file FROM cowpay_staging.users where is_merchant=1"""

cursor = conn_mysql.cursor()
cursor.execute(select_Usersss)
result = cursor.fetchall()
image_dict={'id':[],'json_image':[]}
for row in result:
    image_id=row[0]

    image_data = [
      {      
    
        "m_commercial_registry_file": [row[1]],
        "m_tax_id_file": [row[2]],"m_personal_id_file": [row[3]]
        
    }
        ]
    image_dict['id'].append(image_id)
    image_dict['json_image'].append(json.dumps(image_data))
#s_json = json.dumps(settings_list)

i_json =pd.DataFrame(image_dict)
#i_json.to_csv('i.csv')
i_json

    #Urls.append(image_data)
    #print(data)
#Urls_json = json.dumps(Urls)
#Urls_json

      id                                         json_image
0      2  [{"m_commercial_registry_file": [null], "m_tax...
1      3  [{"m_commercial_registry_file": [null], "m_tax...
2      4  [{"m_commercial_registry_file": [null], "m_tax...
3      8  [{"m_commercial_registry_file": [null], "m_tax...
4      9  [{"m_commercial_registry_file": [null], "m_tax...
..   ...                                                ...
615  888  [{"m_commercial_registry_file": [null], "m_tax...
616  889  [{"m_commercial_registry_file": [null], "m_tax...
617  890  [{"m_commercial_registry_file": [null], "m_tax...
618  891  [{"m_commercial_registry_file": [null], "m_tax...
619  892  [{"m_commercial_registry_file": [null], "m_tax...

[620 rows x 2 columns]

In [22]:
final=my_data.merge(s_json ,on='id').merge(u_json,on='id').merge(i_json,on='id')
final.to_csv('final.csv',encoding='utf-8-sig')
#lol.to_csv('vat_vs_withholding.csv',encoding='utf-8')
#final.to_csv

In [317]:
import pandas as pd
import mysql.connector as lol
import json
import collections
from sys import path
import pyodbc 



conn_mysql = lol.connect(user='root', password='P@ssw0rd',host='localhost',database='cowpay_staging')
#conn_sql = pyodbc.connect('Driver={SQL Server};''Server=BI-SERVER2022;''Database=Staging_Migration;''Trusted_Connection=yes;')

cursor = conn_mysql.cursor()
my_data = pd.read_sql("SELECT * from cowpay_staging.users where is_merchant=1",conn_mysql)
my_data.to_dict()

# update m_facebook to obj
for key, value in my_data['m_facebook'].items():
    my_data['m_facebook'][key] = {
    "SocialUrl": value,
    "SocialType": {"id": "1", "Name": "Facebook","Icon":"fab fa-facebook-f"}
    }

# update m_linked_in to obj
for key, value in my_data['m_linked_in'].items():
    my_data['m_linked_in'][key] = {
    "SocialUrl": value,
    "SocialType": {"id": "3", "Name": "LinkedIn","Icon":"fas fa-link"}
    }

# update m_twitter to obj
for key, value in my_data['m_twitter'].items():
    my_data['m_twitter'][key] = {
    "SocialUrl": value,
    "SocialType": {"id": "2", "Name": "Twitter","Icon":"fab fa-twitter"}
    }

# update m_instagram to obj
for key, value in my_data['m_instagram'].items():
    my_data['m_instagram'][key] = {
    "SocialUrl": value,
    "SocialType": {"id": "5", "Name": "m_instagram","Icon":"fas fa-instagram"}
    }

# update m_website to obj
for key, value in my_data['m_website'].items():
    my_data['m_website'][key] = {
    "SocialUrl": value,
    "SocialType": {"id": "4", "Name": "Website","Icon":""}
    }
    
    
print(my_data.columns)
#print(my_data['AttachamentImages'])

C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
C:\Users\Menna\AppData\Local\Temp\ipykernel_819740\2394786962.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  my_data['m_facebook'][key] = {
C:\Users\Menna\AppData\Local\Temp\ipykernel_819740\2394786962.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  my_data['m_linked_in'][key] = {
C:\Users\Menna\AppData\Local\Temp\ipykernel_819740\2394786962.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  my_data['m_twitter'][key] = {
C:\Users\Menna\AppData\Local\Temp\ipykernel_819740\2394786962.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  my_data['m_instagram'][key] = {
C:\Users\Menna\AppData\Local\Temp\ipykernel_819740\2394786962.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  my_data['m_website'][key] = {

Index(['id', 'parent_id', 'name', 'email', 'phone', 'password', 'api_token',
       'remember_token', 'created_at', 'updated_at', 'is_merchant', 'm_sms_id',
       'm_payments_notification', 'm_orders_notification', 'm_country_id',
       'm_city_id', 'm_facebook', 'm_twitter', 'm_linked_in', 'm_instagram',
       'm_about', 'm_website', 'm_logo', 'm_code', 'm_hash_key', 'm_address',
       'm_invoices', 'm_balance', 'm_available_balance',
       'm_min_payout_threshold', 'm_bank_name', 'm_bank_address',
       'm_bank_account_num', 'm_bank_account_name',
       'm_bank_account_holder_name', 'm_bank_account_swift_code',
       'm_callback_url', 'm_ipn_listener_url', 'm_total_received_amount',
       'm_cowpay_commission', 'm_cowpay_payatfawry_percentage_commission',
       'm_cowpay_payatfawry_fixed_commission',
       'm_cowpay_credit_card_percentage_commission',
       'm_cowpay_credit_card_fixed_commission',
       'm_cowpay_collect_percentage_commission',
       'm_cowpay_collect_fixed_commission', 'm_commercial_registry_file',
       'm_tax_id_file', 'm_personal_id_file', 'm_commercial_registry',
       'm_tax_id', 'm_personal_id', 'm_total_sales_per_year', 'm_added_by',
       'm_added_at', 'm_approved_by', 'm_approved_at', 'environment', 'block',
       'name_ar', 'category', 'mid_category', 'contract_file',
       'authorize_signatory_name', 'fawry_sub_merchant', 'cowpay_fees'],
      dtype='object')

In [12]:
import pandas as pd
import mysql.connector as lol
import json
import collections
from sys import path
import pyodbc 



conn_mysql = lol.connect(user='root', password='P@ssw0rd',host='localhost',database='cowpay_staging')
conn_sql = pyodbc.connect('Driver={SQL Server};''Server=BI-SERVER2022;''Database=Staging_Migration;''Trusted_Connection=yes;')

cursor = conn_mysql.cursor()
data = pd.read_sql("SELECT * from cowpay_staging.users where is_merchant=1",conn_mysql)
my_data = data.to_dict()

for key, value in my_data.items():
    if key == "m_facebook":
        facebook = value
    if key == "m_twitter":
        twitter = value
    if key == "m_linked_in":
        linked = value
    if key == "m_instagram":
        instagram = value
    if key == "m_website":
        website = value

SocialLinks_dict = {}
for index, d in enumerate([facebook, twitter, linked, instagram, website]):
    for k, v in d.items():
        if index == 0: #facebook
            SocialLinks_dict.setdefault(k, []).append(json.dumps({
                "SocialUrl": v,
                "SocialType": {"id": "1", "Name": "Facebook", "Icon": "fab fa-facebook-f"}
            }))
        if index == 1: #twitter
            SocialLinks_dict.setdefault(k, []).append(json.dumps({
                "SocialUrl": v,
                "SocialType": {"id": "2", "Name": "Twitter", "Icon": "fab fa-twitter"}
            }))
        if index == 2:  # linked
            SocialLinks_dict.setdefault(k, []).append(json.dumps({
                "SocialUrl": v,
                "SocialType": {"id": "3", "Name": "LinkedIn","Icon":"fas fa-link"}
            }))
        if index == 3:  # instagram
            SocialLinks_dict.setdefault(k, []).append(json.dumps({
                "SocialUrl": v,
                "SocialType": {"id": "5", "Name": "m_instagram","Icon":"fas fa-instagram"}
            }))
        if index == 4:  # website
            SocialLinks_dict.setdefault(k, []).append(json.dumps({
                "SocialUrl": v,
                "SocialType": {"id": "4", "Name": "Website","Icon":""}
            }))

data['SocialLinks'] = SocialLinks_dict.values()
data['SocialLinks']


for key, value in my_data.items():
    if key == "m_tax_id_file":
        TaxIdImageUrls = value
    if key == "m_personal_id_file":
        PersonalIDImageUrls = value   
    if key == "m_commercial_registry_file":
        CommercialRegistrationImageUrls = value
    
  
        
AttachamentImages_dict = {}
for index, d in enumerate([TaxIdImageUrls, PersonalIDImageUrls, CommercialRegistrationImageUrls]):
    for k, v in d.items():
        if index == 0: #facebook
            AttachamentImages_dict.setdefault(k, []).append(json.dumps({
              "TaxIdImageUrls":v
              
            }))      
                                             
        if index == 1: #facebook
            AttachamentImages_dict.setdefault(k, []).append(json.dumps({
              "PersonalIDImageUrls":v
              
            }))
        if index ==2: #facebook
            AttachamentImages_dict.setdefault(k, []).append(json.dumps({
              "CommercialRegistrationImageUrls":v
              
            }))
                                             
data["AttachamentImages"]=AttachamentImages_dict.values()   
#print(data["AttachamentImages"])
data.to_csv('AI_JSON.csv')

C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

In [11]:
%pwd

'C:\\Users\\Menna\\Documents'

In [ ]:

settings_dict={}
for row in result: 
    settings_data = {
           
    {
        "id": row[0],
        "merchantCode": row[1],
        "StatusTypeId": row[1],
        "moreSetting": {"m_callback_url": row[5], "m_payments_notification": row[6],"m_orders_notification":row[7]},
        "limitationNBlocking":[],
        "financialConfig":{"comessions":[{"payMethodType":2,"fixedVal":row[8],"percentage":row[7],"isEnabled":'false' if row[8] is None and row[7] is None else 'true' },
                                         {"payMethodType":1,"fixedVal":row[10],"percentage":row[9],"isEnabled":'false' if row[9] is None and row[10] is None else 'true'},
                                         {"payMethodType":6,"fixedVal":row[12],"percentage":row[11],"isEnabled":'false' if row[11] is None and row[12] is None else 'true'}
                                        ],
        "autoWithdrawal":{"isEnabled":"","peroidType":"","monthDay":"","daysValue":"","day":""},
        "b2b":{"isEnabled":"","fixedVal":"","percentage":""},
        "chashout":{"isEnabled":"","values":[]}},
         "balanceConfiguration":{"m_available_balance":row[13]}
         },
          
  
    }
    #settings_list.append(settings_data)
    #print(data)
#Urls_json = json.dumps(settings_list)
#Urls_json
#data["Settings"]=settings_list.append(json.dumps(settings_data))
#s_json = json.dumps(data["Settings"])
#s_json
# 
#data["Settings"]=json.loads(settings_data)  
#data["Settings"]
#print(data["AttachamentImages"])  
settings_dict.values(settings_data)
#d=json.dumps(settings_dict)
#json_to_python = json.loads(d)
#print (json_to_python)

In [37]:
#conn_sql = pyodbc.connect('Driver={SQL Server};''Server=BI-SERVER2022;''Database=Staging_Migration;''Trusted_Connection=yes;')
#cursor = conn_sql.cursor()
from sqlalchemy import create_engine
MSS_Staging_engine = create_engine("mssql+pymssql://python:python@localhost:1433/Staging_Migration?charset=utf8")
final.to_sql('Staging_Merchant', con=MSS_Staging_engine,schema=None, if_exists='replace')
#engine.execute("SELECT * FROM Staging_Merchant").fetchall()

620