In [1]:
import connections as conn
import df_initilizer as dfi
import pandas as pd
from pandas import NaT
import pyspark.pandas as pds
import json
import dask.dataframe as ddf

WARNING:root:'PYARROW_IGNORE_TIMEZONE' environment variable was not set. It is required to set this environment variable to '1' in both driver and executor sides if you use pyarrow>=2.0.0. pandas-on-Spark will set it for you but it does not work if there is a Spark context already launched.

In [2]:
def Apply_Fawry_Request(row):
    json_ser='''{"paymentExpiry": "1631138500000"}'''
    json_des=json.loads(json_ser)
    json_des["paymentExpiry"]=str(row.paymentExpiry)
    #new_json=
    #return json.dumps(json_des)
    return json.dumps(json_des)#.replace("'", '"')
    #print(json.dumps(json_des))

In [3]:
def Apply_Fawry_Response(row):
    json_ser ='''{"referenceNumber": "7105039001"}'''
    json_des=json.loads(json_ser)
    json_des["referenceNumber"]=str(row.referenceNumber)
    return json.dumps(json_des)

In [4]:
def Apply_Bosta_Request(row):
    json_ser ='''{"address": "ssdaaaassdasd","apartment": 2,"floor": 1,"cityCode": "EG-01","district": "ddd"}'''
    json_des=json.loads(json_ser)
    json_des.update({"address": row.address,"apartment":row.apartment,"floor": row.floor,"cityCode":row.cityCode,"district":row.district})
    return json.dumps(json_des)

In [5]:
def Apply_Akurateko_Request(row):
    json_ser='''{"action":"Sale","cardNumber":"411111******1111","cardExpMonth":"01","cardExpYear":"2024","isTokenized":true,"isRecurring":true,"customerEmail":"doe@example.com","period":null,"initPeriod":null,"times":null,"cardToken":null,"termUrl3ds":null,"transId":null,"recurringToken":null,"recurringFirstTransId":null,"amount":0.0}'''
    json_des=json.loads(json_ser)
    json_des.update({"action":row.action,"cardNumber":row.cardNumber,"cardExpMonth":row.cardExpMonth,"cardExpYear":row.cardExpYear,"isTokenized":row.isTokenized,"isRecurring":row.isRecurring,"customerEmail":row.customerEmail,"period":row.period,"initPeriod":row.initPeriod,"times":row.times,"cardToken":row.cardToken,"termUrl3ds":row.termUrl3ds,"transId":row.transId,"recurringToken":row.recurringToken,"recurringFirstTransId":row.recurringFirstTransId,"amount":row.amount})
    return json.dumps(json_des)

In [6]:
def Apply_Meeza_Request(row):
    json_ser='''{"tahweelQR": null,"mVisaQR": null,"validity": "jhjh","consumerMobileNumber": null,"loyaltyNumber": "asasN","customerLabel": "CL","purposeOfTransaction": "Test","billNumber":"01001920550","convenienceFeeFixed": null,"convenienceFeePercentage": null,"dateTimeLocalTrxn": null,"tip": null,"gatewayTargetMethod": 0,"merchantReferenceId": null,"customerMerchantProfileId": "11111","merchantId": 0,"merchantCode": "00000000-0000-0000-0000-000000000000","amount": 10,"description": "string","paymentGatewayTypeId": 0,"channelType": 0,"customerFirstName": "ahmed","customerLastName": null,"customerMobile": "01008606003","customerEmail": "ahmed@gmail.com","returnURL": null,"isFeesOnCustomer": false,"paymentLinkTypeId": 0,"paymentLinkId": null,"commession": null,"PromoCode": null,"ExtraData": null}'''
    json_des=json.loads(json_ser)
    json_des.update({"tahweelQR": str( row.tahweelQR) ,"mVisaQR": str( row.mVisaQR) ,"validity": str( row.validity) ,"consumerMobileNumber": str( row.consumerMobileNumber) ,"loyaltyNumber": str( row.loyaltyNumber) ,"customerLabel": str( row.customerLabel) ,"purposeOfTransaction": str( row.purposeOfTransaction) ,"billNumber": str( row.billNumber) ,"convenienceFeeFixed": str( row.convenienceFeeFixed) ,"convenienceFeePercentage": str( row.convenienceFeePercentage) ,"dateTimeLocalTrxn": str( row.dateTimeLocalTrxn) ,"tip": str( row.tip) ,"gatewayTargetMethod": str( row.gatewayTargetMethod) ,"merchantReferenceId": str( row.merchantReferenceId) ,"customerMerchantProfileId": str( row.customerMerchantProfileId) ,"merchantId": str( row.merchantId) ,"merchantCode": str( row.merchantCode) ,"amount": str( row.amount) ,"description": str( row.description) ,"paymentGatewayTypeId": str( row.paymentGatewayTypeId) ,"channelType": str( row.channelType) ,"customerFirstName": str( row.customerFirstName) ,"customerLastName": str( row.customerLastName) ,"customerMobile": str( row.customerMobile) ,"customerEmail": str( row.customerEmail) ,"returnURL": str( row.returnURL) ,"isFeesOnCustomer": str( row.isFeesOnCustomer) ,"paymentLinkTypeId": str( row.paymentLinkTypeId) ,"paymentLinkId": str( row.paymentLinkId) ,"commession": str( row.commession) ,"PromoCode": str( row.PromoCode) ,"ExtraData": str( row.ExtraData)})
    return json.dumps(json_des)

In [7]:
# spark = dfi.initialize_spark_object('Order_Transactions')
# spark

In [7]:
# Akurateko_Transactions='''select * from Akurateko_Transactions'''
# Bosta_Transactions= '''select * from Bosta_Transactions '''
# Fawry_Transactions = '''select * from Fawry_Transactions'''
# Meeza_Transactions = '''select * from Meeza_Transactions'''

In [8]:
# lol = pds.read_sql(Fawry_Transactions,conn.CowPay_Production_Simulation_DB_JDBC)
# lol.head()

In [9]:
fawry_df = ddf.read_sql("Fawry_Transactions",conn.CowPay_Production_Simulation_DB,index_col='Transaction_ID')
fawry_df['PGWMetaRequest']=fawry_df.apply(Apply_Fawry_Request,axis=1)
fawry_df['PGWMetaResponse']=fawry_df.apply(Apply_Fawry_Response,axis=1)
fawry_df.head()

c:\ProgramData\Anaconda3\lib\site-packages\dask\dataframe\core.py:5239: UserWarning:
You did not provide metadata, so Dask is running your function on a small dataset to guess output types. It is possible that Dask will guess incorrectly.
To provide an explicit output types or to silence this message, please provide the `meta=` keyword, as described in the map or apply function that you are using.
  Before: .apply(func)
  After:  .apply(func, meta=(None, 'object'))

  warnings.warn(meta_warning(meta))
c:\ProgramData\Anaconda3\lib\site-packages\dask\dataframe\core.py:5239: UserWarning:
You did not provide metadata, so Dask is running your function on a small dataset to guess output types. It is possible that Dask will guess incorrectly.
To provide an explicit output types or to silence this message, please provide the `meta=` keyword, as described in the map or apply function that you are using.
  Before: .apply(func)
  After:  .apply(func, meta=(None, 'object'))

  warnings.warn(meta_warning(meta))

,paymentExpiry,referenceNumber,PGWMetaRequest,PGWMetaResponse
Transaction_ID,,,,
646236,NaT,9133793384,"{""paymentExpiry"": ""NaT""}","{""referenceNumber"": ""9133793384""}"
646237,NaT,9133748513,"{""paymentExpiry"": ""NaT""}","{""referenceNumber"": ""9133748513""}"
646239,NaT,9133768267,"{""paymentExpiry"": ""NaT""}","{""referenceNumber"": ""9133768267""}"
646238,NaT,9133740131,"{""paymentExpiry"": ""NaT""}","{""referenceNumber"": ""9133740131""}"
646242,NaT,9133705315,"{""paymentExpiry"": ""NaT""}","{""referenceNumber"": ""9133705315""}"

In [10]:
Bosta_df = ddf.read_sql("Bosta_Transactions",conn.CowPay_Production_Simulation_DB,index_col='Transaction_ID')
Bosta_df['PGWMetaRequest']=Bosta_df.apply(Apply_Bosta_Request,axis=1)
Bosta_df['PGWMetaResponse']=NaT

Bosta_df.head()

c:\ProgramData\Anaconda3\lib\site-packages\dask\dataframe\core.py:5239: UserWarning:
You did not provide metadata, so Dask is running your function on a small dataset to guess output types. It is possible that Dask will guess incorrectly.
To provide an explicit output types or to silence this message, please provide the `meta=` keyword, as described in the map or apply function that you are using.
  Before: .apply(func)
  After:  .apply(func, meta=(None, 'object'))

  warnings.warn(meta_warning(meta))

,address,apartment,floor,cityCode,district,PGWMetaRequest,PGWMetaResponse
Transaction_ID,,,,,,,
15181,"Street 54, Building 12, Ground Floor,\r\n1s...",None,None,None,None,"{""address"": ""Street 54, Building 12, Ground...",NaT
432070,"112 El Nil St. Dokki, The Greek Rowing Club",None,None,None,None,"{""address"": ""112 El Nil St. Dokki, The Greek R...",NaT
2480,Nasr City,None,None,None,None,"{""address"": ""Nasr City"", ""apartment"": null, ""f...",NaT
951578,None,None,None,None,None,"{""address"": null, ""apartment"": null, ""floor"": ...",NaT
960414,None,None,None,None,None,"{""address"": null, ""apartment"": null, ""floor"": ...",NaT

In [11]:

Akurateko_df = ddf.read_sql("Akurateko_Transactions",conn.CowPay_Production_Simulation_DB,index_col='Transaction_ID')
#Akurateko_df= pd.DataFrame(Akurateko_df.compute())
Akurateko_df['PGWMetaRequest']=Akurateko_df.apply(Apply_Akurateko_Request,axis=1)
Akurateko_df['PGWMetaResponse']=NaT

Akurateko_df.head()

c:\ProgramData\Anaconda3\lib\site-packages\dask\dataframe\core.py:5239: UserWarning:
You did not provide metadata, so Dask is running your function on a small dataset to guess output types. It is possible that Dask will guess incorrectly.
To provide an explicit output types or to silence this message, please provide the `meta=` keyword, as described in the map or apply function that you are using.
  Before: .apply(func)
  After:  .apply(func, meta=(None, 'object'))

  warnings.warn(meta_warning(meta))

,action,cardNumber,cardExpMonth,cardExpYear,isTokenized,isRecurring,customerEmail,period,initPeriod,times,...,redirectUrl,redirectParams,redirectMethod,status,descriptor,authCode,declineReason,creditvoidDate,PGWMetaRequest,PGWMetaResponse
Transaction_ID,,,,,,,,,,,,,,,,,,,,,
830093,None,445815******4961,None,None,None,None,soliman1476@outlook.com,None,None,None,...,None,None,None,None,None,None,None,None,"{""action"": null, ""cardNumber"": ""445815******49...",NaT
830153,None,526439******4303,None,None,None,None,nada_gamal90@hotmail.com,None,None,None,...,None,None,None,None,None,None,None,None,"{""action"": null, ""cardNumber"": ""526439******43...",NaT
830261,None,531677******5119,None,None,None,None,ahmad.salah@gmail.com,None,None,None,...,None,None,None,None,None,None,None,None,"{""action"": null, ""cardNumber"": ""531677******51...",NaT
830276,None,523761******6016,None,None,None,None,samira.negm@gmail.com,None,None,None,...,None,None,None,None,None,None,None,None,"{""action"": null, ""cardNumber"": ""523761******60...",NaT
830284,None,541955******0010,None,None,None,None,mohamedelmeligi@yahoo.com,None,None,None,...,None,None,None,None,None,None,None,None,"{""action"": null, ""cardNumber"": ""541955******00...",NaT

In [12]:
Meeza_df = ddf.read_sql("Meeza_Transactions",conn.CowPay_Production_Simulation_DB,index_col='Transaction_ID')
#Meeza_df= pd.DataFrame(Meeza_df.compute())
Meeza_df['PGWMetaRequest']=Meeza_df.apply(Apply_Meeza_Request,axis=1)
Meeza_df['PGWMetaResponse']=NaT

Meeza_df.head()

c:\ProgramData\Anaconda3\lib\site-packages\dask\dataframe\core.py:5239: UserWarning:
You did not provide metadata, so Dask is running your function on a small dataset to guess output types. It is possible that Dask will guess incorrectly.
To provide an explicit output types or to silence this message, please provide the `meta=` keyword, as described in the map or apply function that you are using.
  Before: .apply(func)
  After:  .apply(func, meta=(None, 'object'))

  warnings.warn(meta_warning(meta))

,tahweelQR,mVisaQR,validity,consumerMobileNumber,loyaltyNumber,customerLabel,purposeOfTransaction,billNumber,convenienceFeeFixed,convenienceFeePercentage,...,customerEmail,returnURL,isFeesOnCustomer,paymentLinkTypeId,paymentLinkId,commession,PromoCode,ExtraData,PGWMetaRequest,PGWMetaResponse
Transaction_ID,,,,,,,,,,,,,,,,,,,,,
975137,None,None,None,None,None,None,None,None,None,None,...,ayat.mustafa@cowpsay.me,None,1.0,None,None,None,None,None,"{""tahweelQR"": ""None"", ""mVisaQR"": ""None"", ""vali...",NaT
975117,None,None,None,None,None,None,None,None,None,None,...,khalf@cowpay.me,None,1.0,None,None,None,None,None,"{""tahweelQR"": ""None"", ""mVisaQR"": ""None"", ""vali...",NaT
896972,None,None,None,None,None,None,None,None,None,None,...,khalf@cowpay.me,https://nic-cart.com/?action=cowpay,NaN,None,None,None,None,None,"{""tahweelQR"": ""None"", ""mVisaQR"": ""None"", ""vali...",NaT
975444,None,None,None,None,None,None,None,None,None,None,...,aalasoliman1@gmail.com,https://successacademy.app/callbacks/cowpay,0.0,None,None,None,None,None,"{""tahweelQR"": ""None"", ""mVisaQR"": ""None"", ""vali...",NaT
975440,None,None,None,None,None,None,None,None,None,None,...,esam.eisa@cowpay.me,None,NaN,None,None,None,None,None,"{""tahweelQR"": ""None"", ""mVisaQR"": ""None"", ""vali...",NaT

In [13]:
# spark = dfi.initialize_spark_object('Json_Order_Transactions')
# spark.stop()

In [16]:
df1= fawry_df[['PGWMetaRequest','PGWMetaResponse']]
df2= Akurateko_df[['PGWMetaRequest','PGWMetaResponse']]
df3= Meeza_df[['PGWMetaRequest','PGWMetaResponse']]
df4= Bosta_df[['PGWMetaRequest','PGWMetaResponse']]

In [17]:
all_data = ddf.concat([df1,df2,df3,df4],sort=False)
all_data.to_sql("OrderTransactions_jsons_Staging",conn.Staging_Migration_DB,if_exists='replace')